### ISSUE TITLE
Google API Dev API Key Restrictions

### ISSUE THREAD

**Issue by Funchhy** [thojou/php-llm-documents#1]
For Example 01-scrape:

Needs activation of at least Custom Search API:
https://console.cloud.google.com/apis/api/customsearch.googleapis.com

and also if the Google API Key is restricted, one needs to enable it:
https://console.cloud.google.com/apis/credentials?project={YOUR_PROJECT_NAME}

**Comment by thojou** [comment]
Hi,

Thank you for reaching out and for reporting this issue. Your feedback is invaluable in improving this project.

I've made an update to the GoogleSearchFactory, enabling restricted site search. You can modify the example as follows:

```php
new GoogleSearchEngineFactory(
    new Client([
        'application_name' => 'YourApplicationName/1.0',
        'developer_key' => GOOGLE_DEVELOPER_KEY,
    ]),
    SEARCH_ENGINE_ID,
    true // Enable restricted site search
),
```

Your contribution is appreciated. Feel free to stay in contact, if you encounter any further issues.

Best regards.
